#
# Copyright (c) 2021 T-Systems International GmbH (Catena-X Consortium)
# Copyright (c) 2022 Robert Bosch Manufacturing Solutions GmbH
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

name: 0 Governance


on: [push]

jobs:
  synchronize-models:
    name: 00 Determine Target Environment
    runs-on: ubuntu-latest
    outputs:
      stage: ${{ steps.setvars.outputs.stage }}
      workspace: ${{ steps.setvars.outputs.workspace }}
      workspace_uppercase: ${{ steps.setvars.outputs.workspace_uppercase }}
      status: ${{ steps.setvars.outputs.status }}

    steps:
      - name: set environment variables
        run: |
          echo "WORKSPACE=int" >> $GITHUB_ENV
          echo "WORKSPACE_UPPERCASE=INT" >> $GITHUB_ENV
          echo "url_prefix=demo" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Execution Permission
        run: |
            chmod 777 .github/*.sh
          
      - name: Check Changes
        id: changes
        uses: jitterbit/get-changed-files@v1
        with:
          # Format of the steps output context.
          # Can be 'space-delimited', 'csv', or 'json'.
          # Default: 'space-delimited'
          format: 'json'
      
      - name: Fetch Access Token
        id: token_request
        env:
          CLIENT_ID: ${{ secrets[format('IDP_CLIENT_ID_{0}', env.WORKSPACE_UPPERCASE)] }}
          CLIENT_SECRET: ${{ secrets[format('IDP_CLIENT_SECRET_{0}', env.WORKSPACE_UPPERCASE)] }}
          IDP_URL: centralidp.${{ env.url_prefix }}.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token
        run: |
          response=$(curl --request POST \
          --url "https://$IDP_URL" \
          --header 'content-type: application/x-www-form-urlencoded' \
          --data-urlencode grant_type=client_credentials \
          --data-urlencode client_id=$CLIENT_ID \
          --data-urlencode client_secret=$CLIENT_SECRET )
          access_token=$( echo $response | jq -r '.access_token' )
          
          # echo $access_token

          if [ $access_token == null ]
          then
            echo "Error: Got empty token"
            exit 1
          fi

          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV
          
      - name: Synchronize
        uses: ./.github/actions/synchronize
        env:
          SEMANTIC_HUB: semantics.${{ env.WORKSPACE }}.demo.catena-x.net/hub/api/v1/models
        with:
          ADDED: ${{ steps.changes.outputs.added }}
          MODIFIED: ${{ steps.changes.outputs.modified }}
          REMOVED:  ${{ steps.changes.outputs.removed }}
          RENAMED: ${{ steps.changes.outputs.renamed  }}
          BRANCH: ${{ github.ref }}